# DataSource Config
spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    #serverTimezone=Asia/Shanghai  ****很重要，使用UTC时时间保存会少一天
    url: jdbc:db2://130.1.15.89:50000/ECDS:currentSchema=DB2INST1;
    username: db2inst2
    password: db2inst2