# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    #serverTimezone=Asia/Shanghai  ****很重要，使用UTC时时间保存会少一天
    url: jdbc:h2:tcp://localhost/~/test
    username: root
    password: root