#端口号
server:
  port: 8088
  servlet:
    context-path: /api
# DataSource Config
spring:
  profiles:
    # 默认使用开发环境
    active: test
  #flyway数据库版本管理
  flyway:
    clean-disabled: true #禁用clean操作
    enabled: false #使flyway生效
    baseline-on-migrate: true #初始化时如果不存在迁移记录表，默认新建一个
    out-of-order: false #防止开发环境下漏掉没来得及apply的文件，产品环境最好设为false
    locations: classpath:/dbScript
  redis:
  #集群模式
    cluster:
      nodes: 130.1.14.125:6049,130.1.14.126:6049,130.1.14.127:6049,130.1.14.128:6049,130.1.14.129:6049,130.1.14.130:6049
      max-redirects: 3  # 获取失败 最大重定向次数
    password: rxtd@123

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  # pojo包地址，多个使用逗号隔开，不能使用*和classpath
  type-aliases-package: com.zdinit.icecream.auth.vo
#  configuration:
##    #输出格式化sql，但是结果也会输出，过于庞大
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





client:
  ip: 127.0.0.1
  port: 5000

